// Regenerates docs/reference/cli.md from the CLI's own --help output, so the
// reference can't drift from the code. `bun test` fails when it's stale.
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
export const REFERENCE_PATH = join(ROOT, "docs/reference/cli.md");

// Order matches how the docs introduce them, not the CLI's registration order.
const COMMANDS = ["configure", "sync", "list", "stats", "search", "memory", "memory list", "memory classify", "memory summary", "memory delete", "project", "project list", "project add", "export", "classify", "review", "tui", "archive", "unarchive", "delete", "rename"];

function help(args: string[]): string {
	// Piped stdout isn't a TTY, so commander wraps at its fixed default width and
	// the output is identical on every machine.
	const proc = Bun.spawnSync(["bun", join(ROOT, "src/cli.ts"), ...args, "--help"]);
	if (proc.exitCode !== 0) throw new Error(`chatgpt ${args.join(" ")} --help failed: ${proc.stderr.toString()}`);
	return proc.stdout.toString().trimEnd();
}

export function renderReference(): string {
	const sections = COMMANDS.map((c) => `## \`chatgpt ${c}\`\n\n\`\`\`text\n${help(c.split(" "))}\n\`\`\``);
	return `<!-- Generated by scripts/gen-cli-reference.ts from --help output. Edit the command definitions in src/cli.ts, then run \`bun run docs:cli\`. -->

# CLI reference

Every command and flag, taken from \`chatgpt <command> --help\`.

Shared behaviour:

- **Filters.** \`--older-than\`, \`--newer-than\`, \`--before\`, \`--after\`, \`--title\`, \`--archived\`, \`--all\`, \`--limit\`, \`--suggest\`, \`--topic\` and \`--brainstorm\` work the same on every command that lists them. They read the local index, so run \`chatgpt sync\` first.
- **Targets.** Commands that take \`[ids...]\` accept full ids, unique id prefixes, or \`-\` to read ids from stdin (the first column of \`list\` output works).
- **Pinned chats.** Bulk commands skip pinned chats unless you pass \`--pinned\`.
- **Recommendations.** Preview with \`archive --suggest archive --dry-run\` or \`delete --suggest delete --dry-run\`, then repeat without \`--dry-run\` to apply. Both commands skip unsure \`?\` chats. Deletion sends up to three requests at a time.
- **Output.** Results go to stdout; progress, prompts and errors go to stderr, so piping \`list\` into another command stays clean.
- **Exit codes.** \`0\` on success, \`1\` when the command fails or any item in a bulk action fails.

## \`chatgpt\`

\`\`\`text
${help([])}
\`\`\`

${sections.join("\n\n")}
`;
}

if (import.meta.main) {
	await Bun.write(REFERENCE_PATH, renderReference());
	console.error(`wrote ${REFERENCE_PATH}`);
}
